#!/bin/sh

wl-paste --watch cliphist store >/dev/null 2>&1 &

swaybg -c "#002b36" >/dev/null 2>&1 &

# bindsym $mod+h &

# Configure output directives such as mode, position, scale and transform.
# Use wlr-randr to get your output names
# Example ~/.config/kanshi/config below:
#   profile {
#     output HDMI-A-1 position 1366,0
#     output eDP-1 position 0,0
#   }

lxqt-policykit-agent >/dev/null 2>&1 &

# Audio things

# pipewire 2>&1 &
# pipewire-pulse 2>&1 &
# wireplumber 2>&1 &
basically-soundsystem.sh >/dev/null 2>&1 &

# Auto Monitor Configuration
kanshi >/dev/null 2>&1 &

# Launch a panel such as yambar or waybar.
# xfce4-panel >/dev/null 2>&1 &
launch-waybar >/dev/null 2>&1 &

# Enable notifications. Typically GNOME/KDE application notifications go
# through the org.freedesktop.Notifications D-Bus API and require a client such
# as mako to function correctly. Thunderbird is an example of this.
mako >/dev/null 2>&1 &

fcitx --replace >/dev/null 2>&1

nm-applet --indicator >/dev/null 2>&1 &

blueman-applet >/dev/null 2>&1 &

# xwaylandvideobridge >/dev/null 2>&1 &

# Lock screen after 5 minutes
#
# Note that we do not yet support turning off displays in the context of idle
# system power management. Disabling outputs, for example by
# `wlr-randr --output whatever --off` re-arranges views (since a837fefc),
# so is not a good idea.
# A swayidle-friendly implementation may be written using
# wlr-output-power-management-unstable-v1.xml and could then work with a client
# such as https://git.sr.ht/~leon_plickat/wlopm
# sfwbar &

mpd ~/.config/mpd/mpd.conf

light -N 0.5

swayidle -w timeout 1800 'swaylock -f -c 000000' >/dev/null 2>&1 & # 30 menit
